resource_manifest_version "44febabe-d386-4d18-afbe-5e627f4af937"

description "ESX Inventory HUD"

version "1.1"

ui_page "html/ui.html"

client_scripts {
  "@es_extended/locale.lua",
  "client/main.lua",
  "client/trunk.lua",
  "client/property.lua",
  "client/player.lua",
  "locales/cs.lua",
  "locales/en.lua",
  "locales/fr.lua",
  "config.lua"
}

server_scripts {
  "@es_extended/locale.lua",
  "server/main.lua",
  "locales/cs.lua",
  "locales/en.lua",
  "locales/fr.lua",
  "config.lua"
}

files {
  "html/ui.html",
  "html/css/ui.css",
  "html/css/materialize.css",
  "html/css/jquery-ui.css",
  "html/js/inventory.js",
  "html/js/config.js",
  -- JS LOCALES
  "html/locales/cs.js",
  "html/locales/en.js",
  "html/locales/fr.js",
  -- IMAGES


 "html/img/items/cangrejos.png",
 "html/img/items/camarones.png",
 "html/img/items/cajadecangrejos.png",
 "html/img/items/cajadecamarones.png",

 "html/img/items/fishbait.png",
 "html/img/items/shark.png",
 "html/img/items/turtle.png",
 "html/img/items/turtlebait.png",
"html/img/items/contrat.png",
  "html/img/items/bullet.png",
   "html/img/bullet.png",
  "html/img/items/bulletproof.png",
  "html/img/items/advancedlockpick.png",
  "html/img/items/tel.png",
  "html/img/items/nitro.png",
  "html/img/items/sim.png",
  "html/img/items/vine.png",
  "html/img/items/raisin_juice.png",
  "html/img/items/grand_cru.png",
  "html/img/items/raisin.png",
  "html/img/items/fish.png",
  "html/img/items/fishingrod.png",
  "html/img/items/bait.png",
  "html/img/items/bandage.png",
  "html/img/items/beer.png",
  "html/img/items/binoculars.png",
  "html/img/items/bread.png",
  "html/img/items/cannabis.png",

   "html/img/items/wheel.png",
  "html/img/items/clip.png",
  "html/img/items/cocacola.png",
  "html/img/items/coffee.png",
  "html/img/items/coke.png",
  "html/img/items/coke_pooch.png",
  "html/img/items/meth.png",
  "html/img/items/meth_pooch.png",
  "html/img/items/opium.png",
  "html/img/items/opium_pooch.png",
  "html/img/items/weed.png",
  "html/img/items/weed_pooch.png",
  "html/img/items/gold.png",
  "html/img/items/icetea.png",
  "html/img/items/sandwich.png",
  "html/img/items/papers.png",
  "html/img/items/hamburger.png",
  "html/img/items/wine.png",
  "html/img/items/cash.png",
  "html/img/items/chocolate.png",
  "html/img/items/iron.png",
  "html/img/items/jewels.png",
  "html/img/items/diamond.png",
  "html/img/items/rolex.png",
  "html/img/items/ring.png",
  "html/img/items/laptop.png",
  "html/img/items/lockpick.png",
  "html/img/items/drill.png",
  "html/img/items/blowtorch.png",
  "html/img/items/medikit.png",
  "html/img/items/blackspray.png",

  "html/img/items/yusuf.png",
  
  "html/img/items/bluespray.png",
  "html/img/items/greenspray.png",
  "html/img/items/orangespray.png",
  "html/img/items/pinkspray.png",
  "html/img/items/purplespray.png",
  "html/img/items/redspray.png",
  "html/img/items/whitespray.png",
  "html/img/items/tequila.png",
  "html/img/items/whisky.png",
  "html/img/items/limonade.png",
  "html/img/items/phone.png",
  "html/img/items/vodka.png",
  "html/img/items/water.png",
  "html/img/items/cupcake.png",
  "html/img/items/drpepper.png",
  "html/img/items/energy.png",
  "html/img/items/cashewnut.png",
  "html/img/items/peanut.png",
  "html/img/items/pistachionut.png",
  "html/img/items/fixkit.png",
  "html/img/items/potatochips.png",
  "html/img/items/black_chip.png",
  "html/img/items/black_money.png",
  "html/img/items/gym_membership.png",
  "html/img/items/WEAPON_APPISTOL.png",
  "html/img/items/WEAPON_ASSAULTRIFLE.png",
  "html/img/items/WEAPON_ASSAULTSHOTGUN.png",
  "html/img/items/WEAPON_BOTTLE.png",
  "html/img/items/WEAPON_BULLPUPRIFLE.png",
  "html/img/items/WEAPON_CARBINERIFLE.png",
  "html/img/items/WEAPON_COMBATMG.png",
  "html/img/items/WEAPON_BAT.png",
  "html/img/items/WEAPON_COMBATPISTOL.png",
  "html/img/items/WEAPON_CROWBAR.png",
  "html/img/items/WEAPON_GOLFCLUB.png",
  "html/img/items/WEAPON_GUSENBERG.png",
  "html/img/items/WEAPON_KNIFE.png",
  "html/img/items/WEAPON_MICROSMG.png",
  "html/img/items/WEAPON_NIGHTSTICK.png",
  "html/img/items/WEAPON_HAMMER.png",
  "html/img/items/WEAPON_PISTOL.png",
  "html/img/items/WEAPON_PUMPSHOTGUN.png",
  "html/img/items/WEAPON_SAWNOFFSHOTGUN.png",
  "html/img/items/WEAPON_SMG.png",
  "html/img/items/WEAPON_STUNGUN.png",
  "html/img/items/WEAPON_SPECIALCARBINE.png",
  "html/img/items/WEAPON_KNUCKLE.png",
  "html/img/items/WEAPON_FLASHLIGHT.png",
  "html/img/items/WEAPON_REVOLVER.png",
  "html/img/items/WEAPON_DAGGER.png",
  "html/img/items/WEAPON_PETROLCAN.png",
  "html/img/items/WEAPON_PISTOL50.png",
  "html/img/items/WEAPON_DBSHOTGUN.png",
  "html/img/items/WEAPON_SWITCHBLADE.png",
  "html/img/items/WEAPON_POOLCUE.png", --addons from 6/30/19 and after
  "html/img/items/WEAPON_SNSPISTOL.png",
  "html/img/items/WEAPON_PARACHUTE.png",
  "html/img/items/WEAPON_FLAREGUN.png",
  "html/img/items/WEAPON_MOLOTOV.png",
  "html/img/items/WEAPON_BULLPUPSHOTGUN.png",
  "html/img/items/WEAPON_COMPACTRIFLE.png",
  "html/img/items/WEAPON_COMBATPDW.png",
  "html/img/items/poolreceipt.png",
  "html/img/items/tunerchip.png",
  "html/img/items/blindfold.png",
  "html/img/items/grip.png",
  "html/img/items/flashlight.png",
  "html/img/items/silencieux.png",
  "html/img/items/SmallArmor.png",
  "html/img/items/MedArmor.png",
  "html/img/items/HeavyArmor.png",
  "html/img/items/cigarette.png",
  "html/img/items/cigarettepack.png",
  "html/img/items/lighter.png",
  "html/img/items/pistolAmmo.png",
  "html/img/items/shotgunAmmo.png",
  "html/img/items/rifleAmmo.png",
  "html/img/items/machinegunAmmo.png",
  "html/img/items/firstaidkit.png",
  "html/img/items/bitcoin.png"
}